Categories:
Cafe - 0
Food - 1
Nightlife - 2
Grocery - 3
Clothing - 4
Educational - 5
Medical - 6

[[1,2], [1], [1], [1], [], [1], [2], [2], [1,2], [1,2], [3], [3], [1,2], [1],
[4], [1], [1], [1], [1], [1], [1], [1], [1], [], [1], [1], 
[4], [1], [1], [0], [1], [2], [1], [2], [], [0], 
[1,2], [1], [0], [1], [0], [2], [0], [1], [5], [], [4,5],
[2], [1], [2], [3], [1], [1], [3,6], [1], [1], [3,6],[1],
[1],[1], [],[1],[1],[1],[1],[5],[1],[3,6],[1],[4],
[3],[1],[1],[5],[0],[2],[2],[1],[1],[1],[0],[0],[1],[1],
[1],[1],[4],[1],[1],[1],[1],[1],[2],[1],[5],[6],[6],[1],
[],[3],[1],[1],[5],[0],[],[0],[1,2],[2],[1],[5],
[],[],[5],[1],[0],[1],[4],[],[0],[0,1],[5],[0,1],[1],
[1],[4],[],[1],[6],[],[1],[1],[0],[1],[1,3],[1],[],
[1],[0],[1],[6],[6],[],[],[1],[0,1],[4],[3],[],
[1],[],[6],[1],[6],[1],[6],[1],[1],[3],[6],[0],[5],
[4],[1],[4],[1],[],[0,1],[6],[5],[6],[],[],[],[3],
[4],[2],[6],[],[],[3],[2],[3],[],[],[6],[0],[0],[],
[1],[],[5],[5],[],[],[0,1],[],[3],[],[3]]

["Middle East Restaurant and Nightclub",
"Area Four",
"Toscanini's Ice Cream",
"Veggie Galaxy",
"Central Square Florist",
"The Friendly Toast",
"Lord Hobo",
"Cambridge Brewing Company",
"Green Street",
"Meadhall",
"Whole Foods Market",
"Star Market",
"Asgard Irish Pub & Restaurant",
"Sidney's Grille",
"The Garment District",
"Legal Sea Foods",
"Catalyst",
"Flour Bakery",
"Craigie On Main",
"Life Alive",
"The Blue Room",
"Evoo Restaurant",
"Black Sheep Restaurant",
"U-Haul Moving & Storage at Central Square",
"Koreana",
"Thelonious Monkfish",
"Boston Costume",
"Cuchi Cuchi",
"Flat Top Johnny's",
"Cafe Luna",
"Cosi",
"The Phoenix Landing",
"Bondir Restaurant",
"NAGA Restaurant",
"FedEx Office Print & Ship Center",
"1369 Coffee House",
"Miracle of Science Bar & Grill",
"Abigail's Restaurant",
"Voltage Coffee & Art",
"West Bridge",
"Starbucks",
"Tavern in the Square",
"Andala Coffee House",
"Bertucci's",
"Pandemonium Books & Games",
"Cambridge Bicycle",
"MIT Coop",
"Middlesex Lounge",
"Emma's",
"Central Bottle Wine & Provisions",
"Harvest Co-Op Markets",
"Central Kitchen",
"Za Restaurant",
"Walgreens",
"Asmara Restaurant",
"Fuji at Kendall",
"MIT Coop",
"Four Burgers",
"Rangzen Tibetan Place",
"Pepper Sky's",
"Economy True Value",
"India Pavilion",
"Zuzu",
"Chipotle Mexican Grill",
"McDonald's",
"Artist & Craftsman Supply Cambridge",
"Mary Chung",
"CVS Pharmacy - Photo",
"Royal East Restaurant",
"The Goodwill Store",
"Shalimar India Food & Spices",
"Chicago Pizza",
"Amelia's Trattoria",
"Quantum Books",
"Dunkin' Donuts",
"The Field Pub",
"BELLY wine bar",
"Atasca",
"Salts",
"Desi Dhaba",
"Baraka Cafe",
"BeanTowne",
"Sebastians",
"Zephyr On the Charles",
"Cinderella's Restaurant",
"Beantown Taqueria",
"Teddy Shoes, Inc.",
"Beauty's Pizza",
"Kika Tapas",
"Shalimar Of India Restaurant",
"Izzy's Restaurant & Sub Shop",
"Moody's Falafal Palace",
"Libby's Liquor Market Inc",
"Anna's Taqueria",
"Blick Art Materials",
"OmniGuide",
"Genzyme Corporation",
"SUBWAY",
"CORT Furniture Rental & Clearance Center",
"Central Square Farmers Market",
"Brick & Mortar",
"Dosa Factory",
"Rodney's Bookstore",
"Starbucks",
"Advance Tire Company",
"Pacific Street Cafe",
"Champions",
"Firebrand Saints",
"Beijing Tokyo",
"Ambit Creative Group / Minuteman Press of Cambridge",
"Cheapo Records",
"Bedworks, Inc.",
"MIT Press Bookstore",
"Quiznos",
"Dunkin' Donuts",
"ABC Pizza House",
"Ten Thousand Villages",
"Q Audio",
"Rebecca's Cafe",
"Au Bon Pain",
"University Stationery Co",
"Tatte Bakery & Cafe",
"Mexicali Burrito Co",
"Camie's",
"Le Couturier House of Alterations",
"Sleepy's Cambridge",
"7-Eleven",
"Custom Eyes",
"RadioShack",
"Mass Chicken",
"Momogoose Food Truck",
"Dunkin' Donuts",
"Mariposa Bakery",
"Kendall Market & Deli",
"7-Eleven",
"T-Mobile Cambridge",
"Clover Food Truck",
"Starbucks",
"Subway",
"Molecular Insight Pharmaceuticals",
"AVEO Pharmaceuticals Inc",
"LaFreniere Architects Inc",
"Pill Hardware",
"Brookline Lunch",
"Au Bon Pain",
"Expressions",
"LaVerde's Market",
"Xylem",
"Bytes",
"Kendall Flower Shop",
"Harvard Square Eye Care",
"Kendall Kitchen",
"Alkermes Inc",
"Bon Me",
"Millennium Landsdown",
"Sunoco Gas Station",
"Chipotle Mexican Grill",
"Newtowne Variety",
"Proteostasis Therapeutics, Inc.",
"Cafe Spice",
"Window Book Inc",
"Payless ShoeSource",
"World One cuisine",
"Blink High End",
"Edible Arrangements",
"Demiurge Studios",
"Dunkin' Donuts",
"Seventh Sense Biosystems",
"Seven Stars Inc",
"Aileron Therapeutics Inc",
"Computer Sciences Corporation",
"Metropolitan Pipe & Supply Co",
"Boston Area Diving",
"O'Connell's Convenience Plus",
"Boomerangs",
"Parkingway Wines Inc",
"Bio Merieux Inc",
"Cambridge Brands Inc",
"Neighborhood Hardwood Group",
"Columbia Market",
"Supreme Liquors",
"Pearl Street Market",
"Reliable Shade & Screen Co",
"Sleep a Rama",
"Geoffrey A. White, OD",
"Tatte Bakery & Cafe",
"Expresso Cafe",
"Fran-Dan Corporation",
"Beijing Tokyo",
"Cambridge Analytic Couch",
"Utrecht Art Supplies",
"PDQ Instant Printing is Now Kendall Press",
"B P American",
"Frugal Auto",
"Au Bon Pain",
"Wellmet Project Inc.",
"Lucky Corner",
"AT&T Cambridge",
"Fresh Mart"
]